package resource

/*
This file is autogenerated, do not edit;
changes will be undone by the next 'generate' command.

Updates to this type are made my editing the schema file
and executing the 'generate' command
*/

// Model is autogenerated from the json schema
type Model struct {
	Name                     *string             `json:",omitempty"`
	RoleArn                  *string             `json:",omitempty"`
	Version                  *string             `json:",omitempty"`
	ResourcesVpcConfig       *ResourcesVpcConfig `json:",omitempty"`
	Arn                      *string             `json:",omitempty"`
	CertificateAuthorityData *string             `json:",omitempty"`
	ClusterSecurityGroupId   *string             `json:",omitempty"`
	Endpoint                 *string             `json:",omitempty"`
}

// ResourcesVpcConfig is autogenerated from the json schema
type ResourcesVpcConfig struct {
	SecurityGroupIds []string `json:",omitempty"`
	SubnetIds        []string `json:",omitempty"`
}
